version: '3.7'

services: 

  nginx:
    build: ./nginx
    volumes: 
      - static_volume:/usr/src/app/static
    ports:
      - "8001:8001"
    depends_on: 
      - score_web

  score_web:
    build: .
    volumes: 
      - static_volume:/usr/src/app/static
    env_file: 
      - ./.env
    depends_on: 
      - db

  db:
    image: postgres:13.0-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Administrator
      - POSTGRES_DB=flapperbird_deploy
    command: -p 5433

volumes:
  postgres_data:
  static_volume:
